workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: 15.0
    scripts:
      - name: Install XcodeGen from GitHub
        script: |
          curl -Lo xcodegen.zip https://github.com/yonaskolb/XcodeGen/releases/download/2.38.0/xcodegen.zip
          unzip xcodegen.zip
          chmod +x xcodegen
          sudo mv xcodegen /usr/local/bin/
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Build iOS App
        script: |
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO xcodebuild -project LMStudioChat.xcodeproj -scheme LMStudioChat -configuration Release -archivePath build/LMStudioChat.xcarchive archive
    artifacts:
      - build/LMStudioChat.xcarchive
    publishing:
      email:
        recipients:
          - a.s.199191@gmail.com