workflows:
    ios-workflow:
      name: iOS Build
      max_build_duration: 60
      instance_type: mac_mini_m1
      environment:
        xcode: 15.0
        cocoapods: default
      scripts:
        - name: Update Homebrew
          script: |
            brew update
        - name: Install XcodeGen
          script: |
            brew install xcodegen || brew upgrade xcodegen
        - name: Generate Xcode Project
          script: |
            xcodegen generate
        - name: Build iOS App
          script: |
            xcodegen build --scheme LMStudioChat
      artifacts:
        - build/ios/ipa/*.ipa
      publishing:
        email:
          recipients:
            - a.s.199191@gmail.com