workflows:
    ios-workflow:
      name: iOS Build
      max_build_duration: 60
      instance_type: mac_mini_m1
      environment:
        xcode: 15.0
      scripts:
        - name: Install Mint
          script: |
            if ! command -v mint &> /dev/null; then
              brew install mint
            fi
        - name: Install XcodeGen via Mint
          script: |
            mint install yonaskolb/XcodeGen@2.38.0
        - name: Generate Xcode Project
          script: |
            mint run xcodegen@2.38.0 generate
        - name: Build iOS App
          script: |
            xcodebuild -project LMStudioChat.xcodeproj \
              -scheme LMStudioChat \
              -sdk iphoneos \
              -configuration Release \
              -archivePath build/LMStudioChat.xcarchive \
              archive \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
        - name: Package App
          script: |
            mkdir -p build/ios/ipa
            cp -r build/LMStudioChat.xcarchive/Products/Applications/*.app build/ios/ipa/ 2>/dev/null || echo "No app found, checking archive structure..."
            ls -la build/LMStudioChat.xcarchive/Products/ || true
      artifacts:
        - build/ios/ipa
        - build/LMStudioChat.xcarchive
      publishing:
        email:
          recipients:
            - a.s.199191@gmail.com