name: LMStudioChat
options:
  bundleIdPrefix: com.deinname
  deploymentTarget:
    iOS: "16.4"
  developmentLanguage: de
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: $(TARGET_NAME)
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0

targets:
  LMStudioChat:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - Sources
    resources:
      - Resources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: LMStudioChat
        CFBundleIdentifier: com.deinname.lmstudiochat
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.deinname.lmstudiochat
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "16.4"
